version: '3'
services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: authservice
    container_name: authservice
    ports:
      - "9092:9092"

    depends_on:
      - redis
      - keycloak
    environment:
      - KEYCLOAK_REALM=wallet
      - KEYCLOAK_CLIENT_ID=admin-rest-client
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - OTEL_SERVICE_NAME=auth-service
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_JAEGER_TIMEOUT=40000
    networks:
      - digital-wallet-network
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - digital-wallet-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/keycloak/realm.json
    volumes:
      - ./keycloak:/tmp/keycloak
networks:
  digital-wallet-network: { }
